# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openref', '0007_auto_20170419_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='providerupdate',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='providerupdate',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
