# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openref', '0020_auto_20170426_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='providerupdate',
            old_name='providerid',
            new_name='provider',
        ),
    ]
